spring.application.name=gateway-service
server.port=8080
spring.cloud.gateway.x-forwarded.host-enabled=true

spring.cloud.gateway.routes[0].id=medilabo-ui
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**, /login/**, /logout/**, /css/**, /webjars/**, /js/**

spring.cloud.gateway.routes[1].id=patient-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/patient/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=note-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
