spring.application.name=assessment-service
server.port=8084

service.patient.url=http://localhost:8081
service.note.url=http://localhost:8083

#ID for internal security between services.
spring.security.user.name=${S2S_USERNAME}
spring.security.user.password=${S2S_PASSWORD}