spring.application.name=patient-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/medilabo?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

# Security
spring.security.user.name=system-user
spring.security.user.password=admin